### ISSUE TITLE
vfs watch doesn't seem to work as expected

### ISSUE THREAD

**Issue by dolftax** [c9/vfs-local#16]
```
var root = '/home/hacker/workspace'

vfs.watch(root, function() {
  console.log('Something changed')
}
```

What's wrong with the above code?

**Comment by nightwing** [comment]
vfs.watch argument should be relative to workspace root, so if 
`c9.workspaceDir == '/home/hacker/workspace'` watch should be called for `"/"`

```js
vfs.watch("/", function() {
    console.log("Something changed");
}); // also this was missing ;)
```

**Comment by dolftax** [comment]
Humph! Nope!

```
/home/dolftax/doselect/altair/node_modules/vfs-local/localfs.js:861
            callback(null, meta);
            ^
TypeError: undefined is not a function
    at /home/dolftax/doselect/altair/node_modules/vfs-local/localfs.js:861:13
    at check (/home/dolftax/doselect/altair/node_modules/vfs-local/localfs.js:147:13)
    at resolvePath (/home/dolftax/doselect/altair/node_modules/vfs-local/localfs.js:134:14)
    at Object.watch (/home/dolftax/doselect/altair/node_modules/vfs-local/localfs.js:852:9)
    at module.exports (/home/dolftax/doselect/altair/vfs/vfs-interface.js:24:7)
    at Object.<anonymous> (/home/dolftax/doselect/altair/index.js:7:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by nightwing** [comment]
@dolftax are you using this in cloud9 sdk or just this module?
I was answering for client side wrapper, the vfs.watch requires options object see
https://github.com/c9/vfs-local/blob/master/localfs.js#L853

**Comment by dolftax** [comment]
@nightwing Just this module. btw, what `options`? I don't see any mandatory options here - https://github.com/c9/vfs-local#vfswatchpath-options-callback

**Comment by nightwing** [comment]
it says `vfs.watch(path, options, callback)` none of arguments are marked optional, so they are all mandatory.

Call it as
```js
vfs.watch("/", {}, function() {
    console.log("Something changed");
});
```

**Comment by dolftax** [comment]
Nope!

```
  vfs.watch('/', {}, function() {
    console.log('Something changed')
  })
```
.. doesn't seem to work.

I touch a file on the root ('/home/hacker/workspace', which I am passing as `root`) directory, doesn't log anything.

**Comment by nightwing** [comment]
try
```js
vfs.watch("/", {}, function(err, meta) {
    if (err) return console.error(err);
    meta.watcher.on("change", function(e) {
        console.log("change", e);
    });
});
```

**Comment by dolftax** [comment]
@nightwing Works :+1: Thank you. Try documenting these when you find spare time.
